version: '3.9'

services:
  web:
    container_name: django_web_prod
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - ./app/:/app/
      - ./docker-data/static_volume:/home/app/static
      - ./docker-data/media_volume:/home/app/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - my-network

  db:
    container_name: django_postgres_prod
    image: postgres
    restart: always
    volumes:
      - ./docker-data/db_data:/var/lib/postgresql/data/
      - ./docker-data/static_volume:/home/app/static
      - ./docker-data/media_volume:/home/app/media
    env_file:
      - ./.env.db.prod
    expose:
      - 5432
    networks:
      - my-network

  nginx:
    container_name: django_nginx_prod
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-data/static_volume:/home/app/static
      - ./docker-data/media_volume:/home/app/media
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
    external: true
  static_volume:
    external: true
  media_volume:
    external: true
