version: '3.8'

services:
  web:
    container_name: django_web
    build: ./app
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
