version: '3.8'

services:
  web:
    container_name: django_web
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: bash -c "gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    container_name: django_nginx
    build: ./nginx
    volumes:
      - static:/home/app/web/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static:
