version: '3.9'

services:
  web:
    container_name: django_web
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    volumes:
      - ./app:/app
      - /static:/app/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

  nginx:
    container_name: django_nginx
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - /static:/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  db_data: