version: '3.9'

services:
  web:
    container_name: django_web_dev
    build: ./app
    restart: on-failure
    volumes:
      - ./app/:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: django_postgres_dev
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_app

volumes:
  db_data: