version: '3.9'

services:
  web:
    container_name: django_web_prod
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    restart: on-failure
    volumes:
      - ./app/:/app/
      - static_volume:/home/app/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - my-network

  db:
    container_name: django_postgres_prod
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod
    networks:
      - my-network

  nginx:
    container_name: django_nginx_prod
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/home/app/static
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  static_volume:
  db_data: