version: '3.8'

services:
  web:
    container_name: django_web
    build: ./app
    command: bash -c "gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
